version: '3.4'

services:
  couponservicemaster:
    image: couponservicemaster
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3014:3014
