version: '3.4'

services:
  couponservicemaster:
    image: couponservicemaster
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3014:3014
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
